spring.application.name=MobileShop


server.port=8081

Spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.username=root
spring.datasource.password=Pratiksha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

